### PR TITLE
Show how to set global test timeout

### LINKED ISSUE #548: Can we extend timeout recipe to limit every test?
By calling the timeout function in `beforeEach` hook?

```js
context('of 3 seconds in every test', () => {
  beforeEach(() => {
    testTimeout(seconds(3))
  })

  it('runs for 1 second', () => {
    cy.wait(1000)
  })

  it('runs for 5 seconds (should fail)', () => {
    cy.wait(5000)
  })
})
```

Right now seems from the `beforeEach` hook we don't have access to the test to be executed

Screen Shot 2020-08-20 at 1 34 11 PM

### PR DESCRIPTION
**Pull request by bahmutov**
- closes #548

### CODE REVIEW

File: examples/fundamentals__timeout/cypress/integration/all-tests-spec.js [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+  // second attempt: using 'test:before:run' event
+  // this WORKS, make sure to pass the test object
+  // from the event callback's arguments
+  context('of 3 seconds in every test', () => {
+    // IMPORTANT: while this event listener is defined inside a suite
+    // it is called _for every test_.
+    Cypress.on('test:before:run', function (attributes, test) {
+      // during this event, we get the test instance from the arguments
+      testTimeout(seconds(3), test)
+    })
```
Comment (Bkucera) [inline examples/fundamentals__timeout/cypress/integration/all-tests-spec.js:34]: why have it nested in the suite? it would be more clear to have outside all suites

**Review by Bkucera — DISMISSED** [review]
I did not manually verify the code works

File: examples/fundamentals__timeout/cypress/integration/all-tests-spec.js (hunk 1 above)
Comment (bahmutov) [reply examples/fundamentals__timeout/cypress/integration/all-tests-spec.js:34]: because I have another suite of tests (commented) that try to do the same thing using `beforeEach` hook - and I did not want the two approaches to overlap.
